version: '3.3'

services:
  etcd:
    image: quay.io/coreos/etcd
    command: etcd -name etcd0 -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
    network_mode: "host"

  consumer:
    image: registry.cn-qingdao.aliyuncs.com/pangliang/mesh-agent
    command: consumer
    network_mode: "host"

  provider-small:
    image: registry.cn-qingdao.aliyuncs.com/pangliang/mesh-agent
    command: provider-small
    deploy:
      resources:
        limits:
          cpus: '0.60'
    network_mode: "host"

  provider-medium:
    image: registry.cn-qingdao.aliyuncs.com/pangliang/mesh-agent
    command: provider-medium
    deploy:
      resources:
        limits:
          cpus: '1.20'
    network_mode: "host"

  provider-large:
    image: registry.cn-qingdao.aliyuncs.com/pangliang/mesh-agent
    command: provider-large
    deploy:
      resources:
        limits:
          cpus: '1.80'
    network_mode: "host"